name: my-example-voting-app

services:
  redis:
    image: redis:latest # Pulling the latest Redis image from Docker Hub
    networks:
      - default

  db:
    image: postgres:9.4 # Pulling PostgreSQL version 9.4 from Docker Hub
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # Allows all connections without a password
    networks:
      - default

  result:
    build:
      context: ./result # Path to the folder containing the Dockerfile for 'result'
    ports:
      - "5002:80" # Map port 5002 on the host to port 80 in the container
    networks:
      - default

  vote:
    build:
      context: ./vote # Path to the folder containing the Dockerfile for 'vote'
    ports:
      - "5001:80" # Map port 5001 on the host to port 80 in the container
    networks:
      - default

  worker:
    build:
      context: ./worker # Path to the folder containing the Dockerfile for 'worker'
    networks:
      - default

networks:
  default:
    name: my-example-voting-app_default
